{
  imports = [
    ./cava.nix
    ./discord.nix
    ./fuzzel.nix
    ./games.nix
    ./git.nix
    ./guiToolkits.nix
    ./hyfetch.nix
    ./hyprland.nix
    ./i3.nix
    ./nixvim.nix
    ./shell.nix
    ./spotify.nix
    ./sway.nix
    ./swayidle.nix
    ./terminalEmulator.nix
    ./theme.nix
    ./tor.nix
    ./waybar.nix
    ./wofi.nix
  ];
}
